export const ContactConstants = {
  RATE_LIMIT_IP_MAX: 5,
  RATE_LIMIT_WINDOW_SECONDS: 60 * 60,
  RATE_LIMIT_WINDOW_MS: 60 * 60 * 1000,
  IDEMPOTENCY_LOCK_SECONDS: 60,
  IDEMPOTENCY_TTL_SECONDS: 24 * 60 * 60,
} as const;
